version: "3"

x-spark-common: &spark-common
  build:
    context: .
    dockerfile: ./Dockerfile
  volumes:
    - ./config:/opt/bitnami/spark/conf
    - ./jobs:/opt/bitnami/spark/jobs
    - ./jobs:/opt/notebooks
    - ./datasets:/opt/bitnami/spark/datasets
    - ./spark-events:/opt/bitnami/spark/spark-events
  networks:
    - sales


x-spark-worker: &worker
  <<: *spark-common
  command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
  depends_on:
    - spark-master
  environment:
    SPARK_MODE: worker
    SPARK_WORKER_CORES: ${SPARK_WORKER_CORES:-4}
    SPARK_WORKER_MEMORY: ${SPARK_WORKER_MEMORY:-4g}
    SPARK_MASTER_URL: spark://spark-master:7077
    SPARK_RPC_AUTHENTICATION_ENABLED: no
    SPARK_RPC_ENCRYPTION_ENABLED: no
    SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED: no
    SPARK_SSL_ENABLED: no
    SPARK_METRICS_ENABLED: true
  healthcheck:
    test: [ "CMD", "curl", "-f", "http://localhost:8081" ]
    interval: 10s
    timeout: 5s
    retries: 5


services:
  spark-master:
    <<: *spark-common
    container_name: sales-spark-master
    hostname: sales-spark-master
    command: bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "4040:4040"
      - "9090:8080"
      - "7077:7077"
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080" ]
      interval: 5s
      timeout: 3s
      retries: 3

  spark-worker:
    <<: *worker
    container_name: sales-spark-worker-1
    ports:
      - "8081:8081"

  spark-worker-2:
    <<: *worker
    container_name: sales-spark-worker-2
    ports:
      - "8082:8081"

  spark-worker-3:
    <<: *worker
    container_name: sales-spark-worker-3
    ports:
      - "8083:8081"

#  spark-jupyter:
#    build:
#      context: .
#      dockerfile: ./Dockerfile.spark_jupyter
#    container_name: "sales-spark-jupyter"
#    user: root
#    environment:
#      - JUPYTER_ENABLE_LAB="yes"
#      - GRANT_SUDO="yes"
#    volumes:
#      - ./notebooks:/home/jovyan/work
#      - ./notebooks/spark-defaults.conf:/usr/local/spark/conf/spark-defaults.conf
#    ports:
#      - "8888:8888"
#      - "4040:4040"
#    networks:
#      - sales

networks:
  sales:
    driver: bridge

volumes:
  spark-events:
    external: true
  jars:
    external: true

