version: "3"

x-spark-common: &spark-common
  build:
    context: .
    dockerfile: ./Dockerfile
  volumes:
    - ./config:/opt/bitnami/spark/config
    - ./jobs:/opt/bitnami/spark/jobs
    - ./datasets:/opt/bitnami/spark/datasets
    - ./requirements.txt:/requirements.txt
  networks:
    - sales

x-spark-worker: &worker
  <<: *spark-common
  command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
  depends_on:
    - spark-master
  environment:
    SPARK_MODE: worker
    SPARK_WORKER_CORES: 4
    SPARK_WORKER_MEMORY: 4g
    SPARK_MASTER_URL: spark://spark-master:7077
    SPARK_RPC_AUTHENTICATION_ENABLED: no
    SPARK_RPC_ENCRYPTION_ENABLED: no
    SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED: no
    SPARK_SSL_ENABLED: no

services:
  spark-master:
    <<: *spark-common
    container_name: sales-spark-master
    command: bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "9090:8080"
      - "7077:7077"
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no

  spark-worker:
    <<: *worker
    container_name: sales-spark-worker-1

  spark-worker-2:
    <<: *worker
    container_name: sales-spark-worker-2

  spark-worker-3:
    <<: *worker
    container_name: sales-spark-worker-3

networks:
  sales:
    driver: bridge
